# The URL the site will be built for
base_url = "https://whispering-stars.com/"

default_language = "en"

generate_feed = true

theme = "zerm"

compile_sass = true

highlight_code = true

highlight_theme = "axar"

build_search_index = true

taxonomies = [{ name = "tags", feed = true }, { name = "categories" }]

[extra]
author = "SSebigo!"
show_author = true

show_categories = true
show_tags = true

theme_color = "froly"

logo_text = "Whispering Stars"
copyright = "Whispering Stars"

main_menu = [
    { url = "/about/", name = "about" },
    { url = "/contact/", name = "contact" },
]
