# The URL the site will be built for
base_url = "https://whispering-stars.com/"

title = "Whispering Stars"
description = "A place for my thoughts, writings, art and knowledge I don't want to forget."

default_language = "en"

generate_feed = true

theme = "zerm"

compile_sass = true

build_search_index = true

taxonomies = [{ name = "tags", feed = true }, { name = "categories" }]

[markdown]
highlight_code = true

highlight_theme = "gruvbox-dark"

[extra]
author = "SSebigo!"
show_author = true

show_categories = true
show_tags = true

theme_color = "froly"

logo_text = "Whispering Stars"
copyright = "Whispering Stars"

main_menu = [
    { url = "/about/", name = "about" },
    { url = "/contact/", name = "contact" },
]

read_more = "Read more"
