[build]
publish = "public"
command = "rm -rf themes/zerm && git clone https://github.com/ejmg/zerm.git themes/zerm/ && zola build"

[build.environment]
ZOLA_VERSION = "0.18.0"

[context.deploy-preview]
command = "rm -rf themes/zerm && git clone https://github.com/ejmg/zerm.git themes/zerm/ && zola build --base-url $DEPLOY_PRIME_URL"
