name: whispering_stars_website
description: Whispering Stars website
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: 7.8.4
  bloc: 8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  responsive_builder: 0.7.0

dev_dependencies:
  auto_route_generator: 7.3.2
  bloc_test: 9.1.5
  build_runner: 2.4.7
  flutter_test:
    sdk: flutter
  mocktail: 1.0.2
  very_good_analysis: 5.1.0

flutter:
  uses-material-design: true
  generate: true
